name: flutter_mppt_app
description: A Flutter app to monitor MPPT-based solar data via Firebase.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0

flutter:
  uses-material-design: true